#!/usr/bin/env python3

from config import config
from collection import DocumentCollection, TopicCollection
from index import InvertedIndex
from output import output

def main():
    documents = DocumentCollection(config.documents_list)

    # Stopwords may need to go through all documents
    try:
        config.stopwords.initialize_from_data(documents)
    except AttributeError:
        pass

    index = InvertedIndex(documents)     

    topics = TopicCollection(config.topics_list)
    for topic in topics:
        query = topic.title
        result = index.retrieve(query)
        output(topic, result)

        

if __name__ == '__main__':
    main()
