#!/usr/bin/env python3

from config import config
from collection import DocumentCollection, TopicCollection

def main():
    documents = DocumentCollection(config.documents_list)
    topics = TopicCollection(config.topics_list)

    for topic in topics:
        print(topic.title)

if __name__ == '__main__':
    main()
